##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.14.1] date: [Wed May 25 14:32:42 MSK 2022] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = gestureSensor


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og -g1


#######################################
# paths
#######################################
# Build path
BUILD_DIR = .build/debug

######################################
# source
######################################
# C sources
C_SOURCES =  \
Drivers/wiznet_Driver/Src/mqtt_interface.c \
Drivers/wiznet_Driver/Src/MQTTClient.c \
Drivers/wiznet_Driver/Src/httpParser.c \
Drivers/wiznet_Driver/Src/MQTTUnsubscribeServer.c \
Drivers/wiznet_Driver/Src/MQTTPacket.c \
Drivers/wiznet_Driver/Src/dns.c \
Drivers/wiznet_Driver/Src/socket.c \
Drivers/wiznet_Driver/Src/w5500.c \
Drivers/wiznet_Driver/Src/MQTTConnectServer.c \
Drivers/wiznet_Driver/Src/httpServer.c \
Drivers/wiznet_Driver/Src/httpUtil.c \
Drivers/wiznet_Driver/Src/MQTTSerializePublish.c \
Drivers/wiznet_Driver/Src/wizchip_conf.c \
Drivers/wiznet_Driver/Src/MQTTSubscribeClient.c \
Drivers/wiznet_Driver/Src/loopback.c \
Drivers/wiznet_Driver/Src/userHandler.c \
Drivers/wiznet_Driver/Src/MQTTConnectClient.c \
Drivers/wiznet_Driver/Src/MQTTDeserializePublish.c \
Drivers/wiznet_Driver/Src/dhcp.c \
Drivers/wiznet_Driver/Src/MQTTUnsubscribeClient.c \
Drivers/wiznet_Driver/Src/MQTTFormat.c \
Drivers/wiznet_Driver/Src/MQTTSubscribeServer.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_usart.c \
Drivers/w25q/w25qxx.c \
Drivers/apds_9960/apds9960.c \
Middlewares/Third_Party/FatFs/src/ff.c \
Middlewares/Third_Party/FatFs/src/ff_gen_drv.c \
Middlewares/Third_Party/FatFs/src/option/syscall.c \
Middlewares/Third_Party/FatFs/src/option/ccsbcs.c \
Middlewares/Third_Party/FatFs/src/diskio.c \
Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Core/Src/usbd_core.c \
Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Core/Src/usbd_ctlreq.c \
Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Core/Src/usbd_ioreq.c \
Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Class/CDC_ACM/Src/usbd_cdc_acm.c \
Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Class/MSC/Src/usbd_msc_data.c \
Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Class/MSC/Src/usbd_msc.c \
Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Class/MSC/Src/usbd_msc_bot.c \
Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Class/MSC/Src/usbd_msc_scsi.c \
Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Class/HID_KEYBOARD/Src/usbd_hid_kayboard.c \
Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Class/COMPOSITE/Src/usbd_composite.c \
Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Target/usbd_conf.c \
Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/App/usb_device.c \
Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/App/usbd_desc.c \
Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/App/usbd_msc_if.c \
Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/App/usbd_cdc_acm_if.c \
FATFS/Target/user_diskio.c \
FATFS/App/fatfs.c \
Core/gestureConfig/gestureConfig.c \
Core/pwmLed/hsv.c \
Core/pwmLed/PwmLed.c \
Core/Src/dma.c \
Core/Src/spi.c \
Core/Src/main.c \
Core/Src/tim.c \
Core/Src/stm32f4xx_it.c \
Core/Src/ini.c \
Core/Src/sysmem.c \
Core/Src/i2c.c \
Core/Src/system_stm32f4xx.c \
Core/Src/gpio.c \
Core/Src/syscalls.c \
Core/Src/stm32f4xx_hal_msp.c \
Core/Src/usb_otg.c \
Core/Src/usart.c \


# ASM sources
ASM_SOURCES =  \
Core/Startup/startup_stm32f411ccux.s


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32F411xE


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-IComposite \
-ICore \
-ICore/gestureConfig \
-ICore/Inc \
-ICore/pwmLed \
-ICore/Src \
-ICore/Startup \
-IDrivers \
-IDrivers/apds_9960 \
-IDrivers/CMSIS \
-IDrivers/CMSIS/Device \
-IDrivers/CMSIS/Device/ST \
-IDrivers/CMSIS/Device/ST/STM32F4xx \
-IDrivers/CMSIS/Device/ST/STM32F4xx/Include \
-IDrivers/CMSIS/Device/ST/STM32F4xx/Source \
-IDrivers/CMSIS/Include \
-IDrivers/STM32F4xx_HAL_Driver \
-IDrivers/STM32F4xx_HAL_Driver/Inc \
-IDrivers/STM32F4xx_HAL_Driver/Inc/Legacy \
-IDrivers/STM32F4xx_HAL_Driver/Src \
-IDrivers/w25q \
-IDrivers/wiznet_Driver \
-IDrivers/wiznet_Driver/Inc \
-IDrivers/wiznet_Driver/Src \
-IFATFS \
-IFATFS/App \
-IFATFS/Target \
-IMiddlewares \
-IMiddlewares/ST \
-IMiddlewares/ST/STM32_USB_Device_Library \
-IMiddlewares/ST/STM32_USB_Device_Library/Class \
-IMiddlewares/ST/STM32_USB_Device_Library/Class/HID \
-IMiddlewares/ST/STM32_USB_Device_Library/Core \
-IMiddlewares/Third_Party \
-IMiddlewares/Third_Party/AL94_USB_Composite \
-IMiddlewares/Third_Party/AL94_USB_Composite/COMPOSITE \
-IMiddlewares/Third_Party/AL94_USB_Composite/COMPOSITE/App \
-IMiddlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Class \
-IMiddlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Class/CDC_ACM \
-IMiddlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Class/CDC_ACM/Inc \
-IMiddlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Class/CDC_ACM/Src \
-IMiddlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Class/COMPOSITE \
-IMiddlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Class/COMPOSITE/Inc \
-IMiddlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Class/COMPOSITE/Src \
-IMiddlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Class/HID_KEYBOARD \
-IMiddlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Class/HID_KEYBOARD/Inc \
-IMiddlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Class/HID_KEYBOARD/Src \
-IMiddlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Class/MSC \
-IMiddlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Class/MSC/Inc \
-IMiddlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Class/MSC/Src \
-IMiddlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Core \
-IMiddlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Core/Inc \
-IMiddlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Core/Src \
-IMiddlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Target \
-IMiddlewares/Third_Party/FatFs \
-IMiddlewares/Third_Party/FatFs/src \
-IMiddlewares/Third_Party/FatFs/src/option \


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG),1)
CFLAGS += -g3
#-gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32F411CCUX_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	@$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@ ; echo CC    $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	@$(AS) -c $(CFLAGS) $< -o $@ ; echo AS    $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	@$(CC) $(OBJECTS) $(LDFLAGS) -o $@ ; echo LD    $@
	@$(SZ) $@ ; echo SZ    $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	@$(HEX) $< $@ ; echo HEX   $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	@$(BIN) $< $@ ; echo BIN   $@
	
$(BUILD_DIR):
	@mkdir $@ ; echo MKDIR $@

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
